const CAPTION_LANGUAGE_OPTIONS = [
    { value: "af", label: "Afrikaans (af)" },
    { value: "sq", label: "Albanian (sq)" },
    { value: "am", label: "Amharic (am)" },
    { value: "ar", label: "Arabic (ar)" },
    { value: "hy", label: "Armenian (hy)" },
    { value: "az", label: "Azerbaijani (az)" },
    { value: "eu", label: "Basque (eu)" },
    { value: "be", label: "Belarusian (be)" },
    { value: "bn", label: "Bengali (bn)" },
    { value: "bs", label: "Bosnian (bs)" },
    { value: "bg", label: "Bulgarian (bg)" },
    { value: "ca", label: "Catalan (ca)" },
    { value: "ceb", label: "Cebuano (ceb)" },
    { value: "zh", label: "Chinese (zh)" },
    { value: "zh-CN", label: "Chinese (China) (zh-CN)" },
    { value: "zh-HK", label: "Chinese (Hong Kong) (zh-HK)" },
    { value: "zh-SG", label: "Chinese (Singapore) (zh-SG)" },
    { value: "zh-TW", label: "Chinese (Taiwan) (zh-TW)" },
    { value: "zh-Hans", label: "Chinese (Simplified) (zh-Hans)" },
    { value: "zh-Hant", label: "Chinese (Traditional) (zh-Hant)" },
    { value: "co", label: "Corsican (co)" },
    { value: "hr", label: "Croatian (hr)" },
    { value: "cs", label: "Czech (cs)" },
    { value: "da", label: "Danish (da)" },
    { value: "nl", label: "Dutch (nl)" },
    { value: "en", label: "English (en)" },
    { value: "en-AU", label: "English (Australia) (en-AU)" },
    { value: "en-CA", label: "English (Canada) (en-CA)" },
    { value: "en-GB", label: "English (United Kingdom) (en-GB)" },
    { value: "en-IN", label: "English (India) (en-IN)" },
    { value: "en-US", label: "English (United States) (en-US)" },
    { value: "eo", label: "Esperanto (eo)" },
    { value: "et", label: "Estonian (et)" },
    { value: "fil", label: "Filipino (fil)" },
    { value: "fi", label: "Finnish (fi)" },
    { value: "fr", label: "French (fr)" },
    { value: "fr-CA", label: "French (Canada) (fr-CA)" },
    { value: "fr-FR", label: "French (France) (fr-FR)" },
    { value: "fy", label: "Frisian (fy)" },
    { value: "gl", label: "Galician (gl)" },
    { value: "ka", label: "Georgian (ka)" },
    { value: "de", label: "German (de)" },
    { value: "el", label: "Greek (el)" },
    { value: "gu", label: "Gujarati (gu)" },
    { value: "ht", label: "Haitian Creole (ht)" },
    { value: "ha", label: "Hausa (ha)" },
    { value: "haw", label: "Hawaiian (haw)" },
    { value: "he", label: "Hebrew (he)" },
    { value: "hi", label: "Hindi (hi)" },
    { value: "hmn", label: "Hmong (hmn)" },
    { value: "hu", label: "Hungarian (hu)" },
    { value: "is", label: "Icelandic (is)" },
    { value: "ig", label: "Igbo (ig)" },
    { value: "id", label: "Indonesian (id)" },
    { value: "ga", label: "Irish (ga)" },
    { value: "it", label: "Italian (it)" },
    { value: "ja", label: "Japanese (ja)" },
    { value: "jv", label: "Javanese (jv)" },
    { value: "kn", label: "Kannada (kn)" },
    { value: "kk", label: "Kazakh (kk)" },
    { value: "km", label: "Khmer (km)" },
    { value: "rw", label: "Kinyarwanda (rw)" },
    { value: "ko", label: "Korean (ko)" },
    { value: "ku", label: "Kurdish (ku)" },
    { value: "ky", label: "Kyrgyz (ky)" },
    { value: "lo", label: "Lao (lo)" },
    { value: "la", label: "Latin (la)" },
    { value: "lv", label: "Latvian (lv)" },
    { value: "lt", label: "Lithuanian (lt)" },
    { value: "lb", label: "Luxembourgish (lb)" },
    { value: "mk", label: "Macedonian (mk)" },
    { value: "mg", label: "Malagasy (mg)" },
    { value: "ms", label: "Malay (ms)" },
    { value: "ml", label: "Malayalam (ml)" },
    { value: "mt", label: "Maltese (mt)" },
    { value: "mi", label: "Maori (mi)" },
    { value: "mr", label: "Marathi (mr)" },
    { value: "mn", label: "Mongolian (mn)" },
    { value: "my", label: "Myanmar (my)" },
    { value: "ne", label: "Nepali (ne)" },
    { value: "no", label: "Norwegian (no)" },
    { value: "ny", label: "Nyanja (ny)" },
    { value: "or", label: "Odia (or)" },
    { value: "ps", label: "Pashto (ps)" },
    { value: "fa", label: "Persian (fa)" },
    { value: "pl", label: "Polish (pl)" },
    { value: "pt", label: "Portuguese (pt)" },
    { value: "pt-BR", label: "Portuguese (Brazil) (pt-BR)" },
    { value: "pt-PT", label: "Portuguese (Portugal) (pt-PT)" },
    { value: "pa", label: "Punjabi (pa)" },
    { value: "ro", label: "Romanian (ro)" },
    { value: "ru", label: "Russian (ru)" },
    { value: "sm", label: "Samoan (sm)" },
    { value: "gd", label: "Scottish Gaelic (gd)" },
    { value: "sr", label: "Serbian (sr)" },
    { value: "sn", label: "Shona (sn)" },
    { value: "sd", label: "Sindhi (sd)" },
    { value: "si", label: "Sinhala (si)" },
    { value: "sk", label: "Slovak (sk)" },
    { value: "sl", label: "Slovenian (sl)" },
    { value: "so", label: "Somali (so)" },
    { value: "st", label: "Southern Sotho (st)" },
    { value: "es", label: "Spanish (es)" },
    { value: "es-419", label: "Spanish (Latin America) (es-419)" },
    { value: "es-ES", label: "Spanish (Spain) (es-ES)" },
    { value: "su", label: "Sundanese (su)" },
    { value: "sw", label: "Swahili (sw)" },
    { value: "sv", label: "Swedish (sv)" },
    { value: "tg", label: "Tajik (tg)" },
    { value: "ta", label: "Tamil (ta)" },
    { value: "tt", label: "Tatar (tt)" },
    { value: "te", label: "Telugu (te)" },
    { value: "th", label: "Thai (th)" },
    { value: "tr", label: "Turkish (tr)" },
    { value: "tk", label: "Turkmen (tk)" },
    { value: "uk", label: "Ukrainian (uk)" },
    { value: "ur", label: "Urdu (ur)" },
    { value: "ug", label: "Uyghur (ug)" },
    { value: "uz", label: "Uzbek (uz)" },
    { value: "vi", label: "Vietnamese (vi)" },
    { value: "cy", label: "Welsh (cy)" },
    { value: "xh", label: "Xhosa (xh)" },
    { value: "yi", label: "Yiddish (yi)" },
    { value: "yo", label: "Yoruba (yo)" },
    { value: "zu", label: "Zulu (zu)" }
];
